#!/bin/sh
if [ -f /tmp/GlamourAuraFHD-ATV/skin.xml ]; then
  rm -rf /usr/share/enigma2/GlamourAuraFHD-ATV/
  mv /tmp/GlamourAuraFHD-ATV /usr/share/enigma2/
fi
echo "                                                                   "
echo "Now, checking if additional Aura Color skins are already installed " 
if [ -f /tmp/GlamourAuraBerry-ATV/skin.xml ] || [ -f /tmp/GlamourAuraLime-ATV/skin.xml ] || [ -f /tmp/GlamourAuraMango-ATV/skin.xml ] || [ -f /tmp/GlamourAuraRose-ATV/skin.xml ]; then
  echo "Glamour Aura Color skins, found, now updating links to main skin... " 
  echo "                                                                    "
fi
if [ -f /tmp/GlamourAuraBerry-ATV/skin.xml ]; then
  cp -Rs /usr/share/enigma2/GlamourAuraFHD-ATV/* /usr/share/enigma2/GlamourAuraBerry-ATV 2>/dev/null
fi
if [ -f /tmp/GlamourAuraLime-ATV/skin.xml ]; then
  cp -Rs /usr/share/enigma2/GlamourAuraFHD-ATV/* /usr/share/enigma2/GlamourAuraLime-ATV 2>/dev/null
fi
if [ -f /tmp/GlamourAuraMango-ATV/skin.xml ]; then
  cp -Rs /usr/share/enigma2/GlamourAuraFHD-ATV/* /usr/share/enigma2/GlamourAuraMango-ATV 2>/dev/null
fi
if [ -f /tmp/GlamourAuraRose-ATV/skin.xml ]; then
  cp -Rs /usr/share/enigma2/GlamourAuraFHD-ATV/* /usr/share/enigma2/GlamourAuraRose-ATV 2>/dev/null
fi
echo "                                                                        "
echo "Glamour Aura FHD ATV skin is now successfully installed on your receiver"
echo "                       Enjoy!!!                                         "
