#!/bin/sh
if [ -f /tmp/GlamourAuraFHD-ATV/skin.xml ]; then
  rm -rf /usr/share/enigma2/GlamourAuraFHD-ATV/
  mv /tmp/GlamourAuraFHD-ATV /usr/share/enigma2/
fi
echo "                                                                        "
echo "Glamour Aura FHD ATV skin is now successfully installed on your receiver"
echo "                       Enjoy!!!                                         "
