#!/bin/sh
echo "                                                                  "
echo "Glamour Aura FHD ATV skin is now being removed from your receiver."
echo "                                                                  "
